### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by sk3lk0** [davidfoliveira/py-bfurlparser#1]
how i can use it in windows? 
i use pip install bfurlparser and get error in setup

Collecting bfurlparser
  Using cached https://files.pythonhosted.org/packages/f8/cf/52e3467785bc212cc6f32535f3b0a44a104534f57b89425d2fea4fa04523/bfurlparser-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bot\AppData\Local\Temp\pip-install-t72czpu0\bfurlparser\setup.py", line 5, in <module>
        with open("README.rst", "r") as r:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------

its because script have wrong path to README.rst

**Comment by davidfoliveira** [comment]
Hi! Could you submit a PR?

**Comment by sk3lk0** [comment]
Pull requests?
